opencv/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url


from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^loaddb/$', views.loaddb, name='loaddb'),
    url(r'^plates/$', views.showPlates, name='plates'),
    url(r'^visitors/$', views.showVisitors, name='visitors'),
    url(r'^corrected/(?P<pk>[0-9]+)/$', views.showCorrected, name='corrected'),
    url(r'^show/$', views.show, name='show'),
    url(r'^detail_visitor/(?P<spz>[a-zA-Z0-9_]+)/$', views.detail_visitor, name='detail_visitor'),
    url(r'^visitor_edit/$', views.visitor_new, name='visitor_new'),
    url(r'^visitor_edit/(?P<spz>[a-zA-Z0-9_]+)/$', views.visitor_edit, name='visitor_edit'),
    url(r'^detail_plate/(?P<pk>[0-9]+)/$', views.detail_plate, name='detail_plate'),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from PIL import Image





class Visitor(models.Model):
    name = models.CharField(max_length = 200)
    spz = models.CharField(max_length = 10)
    reg_date = models.DateTimeField('date registrated',blank=True,null=True)
    last_visit_date = models.DateTimeField('date visited',blank=True,null=True)
    comment = models.CharField(max_length = 500,blank=True,null=True)
    profile_image = models.ImageField(upload_to='images/profile_pics/',default='images/profile_pics/avatar.png',blank=True,null=True)
    allowed_date_from= models.DateField('allowed_date_from',blank=True,null=True)
    allowed_date_to= models.DateField('allowed_date_to',blank=True,null=True)
    allowed_time_from=models.TimeField('allowed_time_from',blank=True,null=True)
    allowed_time_to=models.TimeField('allowed_time_to',blank=True,null=True)

    def __str__(self):
       return (self.name + " - " + self.spz)

class Plate(models.Model):
    visitor = models.ForeignKey(Visitor, null=True,on_delete=models.CASCADE)
    spz= models.CharField(max_length = 200)
    corrSpz = models.CharField(max_length = 200,blank=True)
    cap_date = models.DateTimeField('date captured')
    image = models.ImageField(upload_to='images/plates')
    corr  = models.ImageField(upload_to='images/corrected',blank=True)
    arr_dep= models.IntegerField(default=0) #arrIVAL =1 depPARTURE = 2 unknown=0
    similarity=models.DecimalField(max_digits=10, decimal_places=8,default=0,blank=True)
    #Simage_url = models.URLField(null=True, blank=True)


    def __str__(self):
       return self.spz

polls/forms.py
from django import forms
from .models import Visitor, Plate
from django.contrib.admin.widgets import AdminDateWidget
from bootstrap3_datetime.widgets import DateTimePicker

class VisitorForm(forms.ModelForm):

    class Meta:
        model = Visitor
        fields = ('name', 'spz','comment','allowed_date_from','allowed_date_to','allowed_time_from','allowed_time_to','profile_image',)
        labels = {
        'name': 'Meno',
        'spz':'Spz',
        'comment':'Komentar',
        'profile_image':'Profilovy obrazok',
        'allowed_date_from':'Povolenie od datumu',
        'allowed_date_to':'Povolenie do datumu',
        'allowed_time_from':'Povolenie od casu',
        'allowed_time_to':'Povolenie do casu',
        }
        help_texts = {
        'name': 'Some useful help text.',
        'allowed_date_from': 'fromat 01.12.2000',
        'allowed_date_to': 'fromat 01.12.2000',
        'allowed_time_from': 'fromat 23:59',
        'allowed_time_to': 'fromat 23:59',
        }
        dateOptions = {
        'format': 'DD.MM.YYYY ',

        }
        timeOptions = {
        'format': 'HH:mm',
        'icons':{'date':'glyphicon glyphicon-time'}


        }
        widgets = {
            'allowed_date_from':DateTimePicker(options=dateOptions),
            'allowed_date_to':DateTimePicker(options=dateOptions),
            'allowed_time_from':DateTimePicker(options=timeOptions,icon_attrs= {'class': 'glyphicon glyphicon-time'}),
            'allowed_time_to':DateTimePicker(options=timeOptions,icon_attrs= {'class': 'glyphicon glyphicon-time'}),
            #'allowed_date_to': AdminDateWidget(),
        }

class PlateForm(forms.ModelForm):

    class Meta:
        model = Plate
        fields = ('corrSpz', )
        labels = {
        'corrSpz': 'Skutocna Spz',
        }
        help_texts = {
        'corrSpz': 'Tu mozes upravit zle rozoznanu SPZ',
        }

polls/views.py
from django.shortcuts import get_object_or_404, render,get_list_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import  Visitor, Plate

from django.db.models.functions import Length

import requests

from .forms import  VisitorForm, PlateForm

from django.shortcuts import redirect

from .helpers import *

from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def add_entry():

    p=Plate(spz="NAME", cap_date=timezone.now(),image=None)
    save_image_from_url(p,'http://192.168.1.21:8080/shot.jpg')
    p.save()

def loaddb(request):
    print ("Saving")
    get_plates_from_spz_to_DB('http://spz.ditis.sk',100)
    plates_l = get_list_or_404(Plate)
    save_corrected_plates(plates_l)
    return render(request, 'polls/loaddb.html')

def show(request):
    print ("Saving")
    return render(request, 'polls/show.html')

def showPlates(request):

    plates_l = Plate.objects.annotate(text_len=Length('spz')).filter(text_len__gte=1)
    plates_l = plates_l.all().order_by('spz')
    #plates_l =get_list_or_404(Plate)
    #plates_l = plates_l.all().order_by('spz')

    return render(request, 'polls/showPlates.html',{'plates_l' : plates_l})

def showVisitors(request):
    visitors_l = get_list_or_404(Visitor)
    return render(request, 'polls/showVisitors.html',{'visitors_l' : visitors_l})

def showCorrected(request,pk):
    plate = get_object_or_404(Plate, pk=pk)
    corrected=do_opencv(plate)
    return render(request, 'polls/showCorrected.html',{'corrected' : corrected})

class HomePage(generic.TemplateView):
    template_name = 'polls/home.html'


def detail_visitor(request,spz):
    try:
        visitor = Visitor.objects.get(spz=spz)
        plates_l = Plate.objects.filter(visitor=visitor)

        all_plate=[]
        uvisitor = Visitor.objects.get(spz='BA000XX')
        all_plates = Plate.objects.filter(visitor=uvisitor)
        #all_plates = Plate.objects.all().exclude(spz=spz)
        for plate in all_plates:
            plate.similarity=similar(visitor.spz,plate.spz)
            plate.save()
        all_plates=all_plates.order_by('-similarity')
        for plate in all_plates:
            if plate.similarity > 0.5:
                all_plate.append(plate)
    except Visitor.DoesNotExist:
        visitor = Visitor.objects.get(spz='BA000XX')
        plates_l = Plate.objects.get(visitor=visitor)
        return render(request, 'polls/detail_visitor.html',{'visitor' : visitor})

    return render(request, 'polls/detail_visitor.html',{'visitor' : visitor , 'plates_l' : plates_l,'all_plate':all_plate,})

def visitor_new(request):
    if request.method == "POST":
        form = VisitorForm(request.POST)
        if form.is_valid():
            print ("je valiad new")
            visitor = form.save(commit=False)
            visitor.reg_date = timezone.now()
            visitor.save()
            uvisitor= Visitor.objects.get(spz='BA000XX')
            plate_l = Plate.objects.filter(visitor=uvisitor)
            print(str(plate_l) + "pred IF")
            if plate_l.filter(spz=visitor.spz):
                for plate in plate_l.filter(spz=visitor.spz):
                    plate.visitor=visitor
                    plate.save()
                    print(str(plate) + "Prve for")
            if plate_l.filter(corrSpz=visitor.spz):
                for plate in plate_l.filter(corrSpz=visitor.spz):
                    plate.visitor=visitor
                    plate.save()
                    print(str(plate) + "Druhe for")



            return redirect('polls:detail_visitor', spz=visitor.spz)
    else:
        form = VisitorForm()
    return render(request, 'polls/visitor_edit.html', {'form': form})

def visitor_edit(request,spz):
    visitor = get_object_or_404(Visitor, spz=spz)
    if request.method == "POST":
        form = VisitorForm(request.POST, instance=visitor)
        if form.is_valid():
            print ("je valiad edit")
            visitor = form.save(commit=False)
            visitor.save()
            return redirect('polls:detail_visitor', spz=visitor.spz)
    else:
        form = VisitorForm(instance=visitor)
    return render(request, 'polls/visitor_edit.html', {'form': form})


###################################################chybovu hlasku ak PK neexistuje
def detail_plate(request,pk):
    try:
        plate = Plate.objects.get(pk=pk)
        if request.method == "POST":
            form = PlateForm(request.POST, instance=plate)
            form.fields['corrSpz'].required = False
            if form.is_valid():

                plate = form.save(commit=False)
                print (plate.corrSpz)
                try:
                    if plate.corrSpz=='':
                        visitor = Visitor.objects.get(spz=plate.spz)
                    else:
                        visitor = Visitor.objects.get(spz=plate.corrSpz)
                except Visitor.DoesNotExist:
                    visitor = Visitor.objects.get(spz='BA000XX')
                plate.visitor = visitor
                plate.save()
                return redirect('polls:detail_plate', pk=plate.pk)
        else:
            form = PlateForm(instance=plate)
        return render(request, 'polls/detail_plate.html', {'plate' : plate,'form': form})
    except Visitor.DoesNotExist:
        print('exce')


    #return render(request, 'polls/detail_plate.html',{'plate' : plate})

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/detail_plate.html
    {% extends 'base.html' %}
    {% block title %}Plate detail{% endblock title %}
    {% block nav-style %}mkt-nav{% endblock nav-style %}

{% block content %}
<div class="w3-container-padding">


  <!-- Page Container -->
  <div class="w3-content w3-margin-top" style="max-width:1400px;">
      <h1>Detail zaznamu</h1>
    <!-- The Grid -->
    <div class="w3-row-padding ">
      <div class="w3-quarter">
        <p></p>
     </div>
      <!-- Left Column -->
      <div class="w3-half">

        <div class="w3-white w3-text-grey w3-card-4 w3-center">
          <div class="w3-display-container">
            <img src="{{plate.image.url}}" style="width:100%" alt="Avatar">
            <div class="w3-display-bottomleft w3-container w3-text-black">
              <h2></h2>
            </div>
          </div>
          <br>
          <div class="w3-container ">
            <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i><b>Majitel  </b>  <a href="{% url 'polls:detail_visitor' spz=plate.visitor.spz %}">{{ plate.visitor }}</a></p>

            <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i><b>SPZ  </b>  {{plate.spz}}</p>
            <hr>
            <form method="POST" class="post-form">{% csrf_token %}
                   <div class="w3-row-padding ">
                     <div class="w3-col s2 m3 l3 ">
                       <p></p>
                    </div>
                     <div class="w3-col s8 m6 l6 ">
                    {% include 'includes/bs4_form.html' with form=form %}
                    </div>
                    </div>
                <button type="submit" class="save btn btn-default">Ulozit</button>

            </form>
            <hr>


          </div>
        </div>


        <br>

      <!-- End Left Column -->
      </div>



    <!-- End Grid -->
    </div>

    <!-- End Page Container -->
  </div>

</div>
{% endblock %}

polls/templates/polls/detail_visitor.html
    {% extends 'base.html' %}
    {% block title %}Visitor profile{% endblock title %}
    {% block nav-style %}mkt-nav{% endblock nav-style %}

{% block content %}
<div class="w3-container-padding">


  <!-- Page Container -->
  <div class="w3-content w3-margin-top" style="max-width:1400px;">
      <h1>Profil navstevnika</h1>
    <!-- The Grid -->
    <div class="w3-row-padding">

      <!-- Left Column -->
      <div class="w3-quarter">

        <div class="w3-white w3-text-grey w3-card-4">
          <div class="w3-display-container">
            <img src="{{visitor.profile_image.url}}" style="width:100%" alt="Avatar">
            <div class="w3-display-bottomleft w3-container w3-text-black">
              <h2>{{ visitor.name }}</h2>
            </div>
          </div>
          <br>
          <div class="w3-container">
            <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i><b>SPZ  </b>  {{visitor.spz}}</p>
            <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i>Pozicia</p>
            <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>Mail</p>
            <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i>Cislo</p>
            <hr>

            <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Komentar</b></p>
            <p>{{visitor.comment}}</p>
            <hr>

            <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Povolenie na vjazd</b></p>
            <p><b>Datum od  </b>{{ visitor.allowed_date_from }}</p>

            <p><b>Datum do  </b>{{ visitor.allowed_date_to }}</p>

            <p><b>Cas od  </b>{{ visitor.allowed_time_from }}</p>

            <p><b>Cas do  </b>{{ visitor.allowed_time_to }}</p>
            <hr>
              <div class="w3-display-container">
                <div class="w3-display-middle w3-container">

                  <a class="btn btn-default" href="{% url 'polls:visitor_edit' spz=visitor.spz %}"><span class="glyphicon glyphicon-pencil"></span> Upravit profil navstevnika</a>

               </div>
            </div>
          <hr>
          </div>
        </div><br>

      <!-- End Left Column -->
      </div>

      <!-- Right Column -->
      <div class="w3-threequarter">



        <div class="w3-container w3-card-2 w3-white">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Zoznam poslednych vstupov</h2>
          <div class="table-responsive" margin="20">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>SPZ</th>
                  <th>Upravena SPZ</th>
                  <th>Cas</th>
                  <th>ObrazokORIGINAL</th>
                  <th>ObrazokCORRECTED</th>
                </tr>
              </thead>
              <tbody>
                {% for plate in plates_l %}
              <tr>
              <td>{{ forloop.counter }}.</td>
              <td><a href="{% url 'polls:detail_plate' pk=plate.pk %}">{{ plate.spz }}</a></td>
              <td>{{ plate.corrSpz }}</td>
              <td>{{ plate.cap_date }}</td>
              <td><img src="{{plate.image.url}}" ></td>
              <td><img src="{{plate.corr.url}}" ></td>
            </tr>


          {% endfor %}

              </tbody>
            </table>
          </div>
        </div>

      <!-- End Right Column -->
      </div>




      <!-- second Right Column -->
      <div class="w3-threequarter">



        <div class="w3-container w3-card-2 w3-white">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Zoznam poslednych moznych vstupov</h2>
          <div class="table-responsive" margin="20">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>SPZ</th>
                  <th>Upravena SPZ</th>
                  <th>Cas</th>
                  <th>Podobnost</th>
                  <th>ObrazokORIGINAL</th>
                  <th>ObrazokCORRECTED</th>
                </tr>
              </thead>
              <tbody>
                {% for plate in all_plate %}

              <tr>
              <td>{{ forloop.counter }}.</td>
              <td><a href="{% url 'polls:detail_plate' pk=plate.pk %}">{{ plate.spz }}</a></td>
              <td>{{ plate.corrSpz }}</td>
              <td>{{ plate.cap_date }}</td>
              <td>{{ plate.similarity }}</td>
              <td><img src="{{plate.image.url}}" ></td>
              <td><img src="{{plate.corr.url}}" ></td>
            </tr>


          {% endfor %}

              </tbody>
            </table>
          </div>
        </div>

      <!-- End  second Right Column -->
      </div>










    <!-- End Grid -->
    </div>

    <!-- End Page Container -->
  </div>

</div>
{% endblock %}

polls/templates/polls/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block nav-style %}mkt-nav{% endblock nav-style %}

{% block content %}

{# Hero Section #}
<div class="mkt-s1">
  <div class="mkt-s1-body container ">
      <div class="row">
          <h1 class="col-md-8">Home Page</h1>
      </div>
  </div>
</div>

{% endblock content %}

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/loaddb.html
    {% extends 'base.html' %}
    {% block title %}Home{% endblock title %}
    {% block nav-style %}mkt-nav{% endblock nav-style %}

    {% block content %}

<p > Successfully loaded images to DB </p>

    {% endblock content %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/save.html
<img src="http://192.168.1.21:8080/shot.jpg" style="width:304px;height:228px;">
<button id="save_button">Save Imgae</button>

polls/templates/polls/show.html
    {% extends 'base.html' %}
    {% block title %}Home{% endblock title %}
    {% block nav-style %}mkt-nav{% endblock nav-style %}

    {% block content %}
    <img id="frame" src="http://192.168.1.21:8080/shot.jpg">

    <script>
        // Use an off-screen image to load the next frame.
        var img = new Image();

        // When it is loaded...
        img.addEventListener("load", function() {

            // Set the on-screen image to the same source. This should be instant because
            // it is already loaded.
            document.getElementById("frame").src = img.src;

            // Schedule loading the next frame.
            setTimeout(function() {
                img.src = "http://192.168.1.21:8080/shot.jpg?" + (new Date).getTime();
            }, 1000/3); // 15 FPS (more or less)
        })

        // Start the loading process.
        img.src = "http://192.168.1.21:8080/shot.jpg?" + (new Date).getTime();
    </script>
    {% endblock content %}

polls/templates/polls/showCorrected.html
    {% extends 'base.html' %}
    {% block title %}Home{% endblock title %}
    {% block nav-style %}mkt-nav{% endblock nav-style %}

    {% block content %}

<img src="{{corrected.url}}"></td>

    {% endblock content %}

polls/templates/polls/showPlates.html
    {% extends 'base.html' %}
    {% block title %}Home{% endblock title %}
    {% block nav-style %}mkt-nav{% endblock nav-style %}

    {% block content %}
    <div class="container-fluid">



        <main class=" ml-sm-auto  pt-3" role="main">
          <h1>Zoznam zaznamov SPZ</h1>

          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Majitel</th>
                  <th>SPZ</th>
                  <th>Upravena SPZ</th>
                  <th>Cas</th>
                  <th>ObrazokORIGINAL</th>
                  <th>ObrazokCORRECTED</th>
                </tr>
              </thead>
              <tbody>
                {% for plate in plates_l %}
            <tr>
              <td>{{ forloop.counter }}.</td>
              <td><a href="{% url 'polls:detail_visitor' spz=plate.visitor.spz %}">{{ plate.visitor }}</a></td>
              <td><a href="{% url 'polls:detail_plate' pk=plate.pk %}">{{ plate.spz }}</a></td>
              <td>{{ plate.corrSpz }}</td>
              <td>{{ plate.cap_date }}</td>
              <td><img src="{{plate.image.url}}" ></td>
              <td><img src="{{plate.corr.url}}" ></td>

            </tr>


          {% endfor %}

              </tbody>
            </table>
          </div>

        </main>

    </div>

    {% endblock content %}

polls/templates/polls/showVisitors.html
    {% extends 'base.html' %}
    {% block title %}Home{% endblock title %}
    {% block nav-style %}mkt-nav{% endblock nav-style %}

    {% block content %}
    <div class="container-fluid">


        <main class=" ml-sm-auto  pt-3" role="main">

          <h2>Zoznam navstevnikov</h2>
          <a class="btn btn-default" href="{% url 'polls:visitor_new' %}" ><span class="glyphicon glyphicon-plus"></span> Pridat navstevnika</a>

          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Meno</th>
                  <th>SPZ</th>
                  <th>Posledna navsteva</th>
                  <th>Obrazok</th>
                </tr>
              </thead>
              <tbody>
                {% for visitor in visitors_l %}
            <tr>
              <td>{{ forloop.counter }}.</td>
              <td><a href="{% url 'polls:detail_visitor' spz=visitor.spz %}"> {{visitor.name}} </a> </td>
              <td><a>{{visitor.spz}} </a></td>
              <td>{{ visitor.last_visit_date }}</td>
              <td><img src="{{visitor.profile_image.url}}" style="width:150px;height:120px;"></td>

            </tr>


          {% endfor %}

              </tbody>
            </table>
          </div>

        </main>

    </div>

    {% endblock content %}

polls/templates/polls/visitor_edit.html
    {% extends 'base.html' %}
    {% block title %}Home{% endblock title %}
    {% block nav-style %}mkt-nav{% endblock nav-style %}

    {% block content %}
    <div class="container-fluid">



        <main class=" ml-sm-auto  pt-3" role="main">
              {% if form.instance.pk == None %}
              <h2>Novy profil navstevnika</h2>
              {% else  %}
              <h2>Uprava navstevnikoveho profilu</h2>
              {% endif  %}

              <form method="POST" class="post-form">{% csrf_token %}
                <div class="row" >

                      <div class="col-sm-4">
                 {% include 'includes/bs4_form.html' with form=form %}
                 </div>





               </div>
               <hr>
                  <button type="submit" class="save btn btn-default">Ulozit</button>
              <hr>
              </form>

        </main>

    </div>

    {% endblock content %}