opencv/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url


from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^loaddb/$', views.loaddb, name='loaddb'),
    url(r'^plates/$', views.showPlates, name='plates'),
    url(r'^visitors/$', views.showVisitors, name='visitors'),
    url(r'^corrected/(?P<pk>[0-9]+)/$', views.showCorrected, name='corrected'),
    url(r'^show/$', views.show, name='show'),
    url(r'^detail_visitor/(?P<spz>[a-zA-Z0-9_]+)/$', views.detail_visitor, name='detail_visitor'),
    url(r'^visitor_edit/$', views.visitor_new, name='visitor_new'),
    url(r'^visitor_edit/(?P<spz>[a-zA-Z0-9_]+)/$', views.visitor_edit, name='visitor_edit'),
    url(r'^detail_plate/(?P<pk>[0-9]+)/$', views.detail_plate, name='detail_plate'),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from PIL import Image





class Visitor(models.Model):
    name = models.CharField(max_length = 200)
    spz = models.CharField(max_length = 10)
    reg_date = models.DateTimeField('date registrated',blank=True,null=True)
    last_visit_date = models.DateTimeField('date visited',blank=True,null=True)
    comment = models.CharField(max_length = 500,blank=True,null=True)
    profile_image = models.ImageField(upload_to='images/profile_pics/',default='images/profile_pics/avatar.png',blank=True,null=True)
    allowed_date_from= models.DateField('allowed_date_from',blank=True,null=True)
    allowed_date_to= models.DateField('allowed_date_to',blank=True,null=True)
    allowed_time_from=models.TimeField('allowed_time_from',blank=True,null=True)
    allowed_time_to=models.TimeField('allowed_time_to',blank=True,null=True)

    def __str__(self):
       return (self.name + " - " + self.spz)

class Plate(models.Model):
    visitor = models.ForeignKey(Visitor, null=True,on_delete=models.CASCADE)
    spz= models.CharField(max_length = 200)
    corrSpz = models.CharField(max_length = 200,blank=True)
    cap_date = models.DateTimeField('date captured')
    image = models.ImageField(upload_to='images/plates')
    corr  = models.ImageField(upload_to='images/corrected',blank=True)
    arr_dep= models.IntegerField(default=0) #arrIVAL =1 depPARTURE = 2 unknown=0
    similarity=models.DecimalField(max_digits=10, decimal_places=8,default=0,blank=True)
    #Simage_url = models.URLField(null=True, blank=True)


    def __str__(self):
       return self.spz

polls/forms.py
from django import forms
from .models import Visitor, Plate
from django.contrib.admin.widgets import AdminDateWidget
from bootstrap3_datetime.widgets import DateTimePicker

class VisitorForm(forms.ModelForm):

    class Meta:
        model = Visitor
        fields = ('name', 'spz','comment','allowed_date_from','allowed_date_to','allowed_time_from','allowed_time_to','profile_image',)
        labels = {
        'name': 'Meno',
        'spz':'Spz',
        'comment':'Komentar',
        'profile_image':'Profilovy obrazok',
        'allowed_date_from':'Povolenie od datumu',
        'allowed_date_to':'Povolenie do datumu',
        'allowed_time_from':'Povolenie od casu',
        'allowed_time_to':'Povolenie do casu',
        }
        help_texts = {
        'name': 'Some useful help text.',
        'allowed_date_from': 'fromat 01.12.2000',
        'allowed_date_to': 'fromat 01.12.2000',
        'allowed_time_from': 'fromat 23:59',
        'allowed_time_to': 'fromat 23:59',
        }
        dateOptions = {
        'format': 'DD.MM.YYYY ',

        }
        timeOptions = {
        'format': 'HH:mm',
        'icons':{'date':'glyphicon glyphicon-time'}


        }
        widgets = {
            'allowed_date_from':DateTimePicker(options=dateOptions),
            'allowed_date_to':DateTimePicker(options=dateOptions),
            'allowed_time_from':DateTimePicker(options=timeOptions,icon_attrs= {'class': 'glyphicon glyphicon-time'}),
            'allowed_time_to':DateTimePicker(options=timeOptions,icon_attrs= {'class': 'glyphicon glyphicon-time'}),
            #'allowed_date_to': AdminDateWidget(),
        }

class PlateForm(forms.ModelForm):

    class Meta:
        model = Plate
        fields = ('corrSpz', )
        labels = {
        'corrSpz': 'Skutocna Spz',
        }
        help_texts = {
        'corrSpz': 'Tu mozes upravit zle rozoznanu SPZ',
        }

polls/views.py
from django.shortcuts import get_object_or_404, render,get_list_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import  Visitor, Plate

from django.db.models.functions import Length

import requests

from .forms import  VisitorForm, PlateForm

from django.shortcuts import redirect

from .helpers import *

from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def add_entry():

    p=Plate(spz="NAME", cap_date=timezone.now(),image=None)
    save_image_from_url(p,'http://192.168.1.21:8080/shot.jpg')
    p.save()

def loaddb(request):
    print ("Saving")
    get_plates_from_spz_to_DB('http://spz.ditis.sk',100)
    plates_l = get_list_or_404(Plate)
    save_corrected_plates(plates_l)
    return render(request, 'polls/loaddb.html')

def show(request):
    print ("Saving")
    return render(request, 'polls/show.html')

def showPlates(request):

    plates_l = Plate.objects.annotate(text_len=Length('spz')).filter(text_len__gte=1)
    plates_l = plates_l.all().order_by('spz')
    #plates_l =get_list_or_404(Plate)
    #plates_l = plates_l.all().order_by('spz')

    return render(request, 'polls/showPlates.html',{'plates_l' : plates_l})

def showVisitors(request):
    visitors_l = get_list_or_404(Visitor)
    return render(request, 'polls/showVisitors.html',{'visitors_l' : visitors_l})

def showCorrected(request,pk):
    plate = get_object_or_404(Plate, pk=pk)
    corrected=do_opencv(plate)
    return render(request, 'polls/showCorrected.html',{'corrected' : corrected})

class HomePage(generic.TemplateView):
    template_name = 'polls/home.html'


def detail_visitor(request,spz):
    try:
        visitor = Visitor.objects.get(spz=spz)
        plates_l = Plate.objects.filter(visitor=visitor)

        all_plate=[]
        uvisitor = Visitor.objects.get(spz='BA000XX')
        all_plates = Plate.objects.filter(visitor=uvisitor)
        #all_plates = Plate.objects.all().exclude(spz=spz)
        for plate in all_plates:
            plate.similarity=similar(visitor.spz,plate.spz)
            plate.save()
        all_plates=all_plates.order_by('-similarity')
        for plate in all_plates:
            if plate.similarity > 0.5:
                all_plate.append(plate)
    except Visitor.DoesNotExist:
        visitor = Visitor.objects.get(spz='BA000XX')
        plates_l = Plate.objects.get(visitor=visitor)
        return render(request, 'polls/detail_visitor.html',{'visitor' : visitor})

    return render(request, 'polls/detail_visitor.html',{'visitor' : visitor , 'plates_l' : plates_l,'all_plate':all_plate,})

def visitor_new(request):
    if request.method == "POST":
        form = VisitorForm(request.POST)
        if form.is_valid():
            print ("je valiad new")
            visitor = form.save(commit=False)
            visitor.reg_date = timezone.now()
            visitor.save()
            uvisitor= Visitor.objects.get(spz='BA000XX')
            plate_l = Plate.objects.filter(visitor=uvisitor)
            print(str(plate_l) + "pred IF")
            if plate_l.filter(spz=visitor.spz):
                for plate in plate_l.filter(spz=visitor.spz):
                    plate.visitor=visitor
                    plate.save()
                    print(str(plate) + "Prve for")
            if plate_l.filter(corrSpz=visitor.spz):
                for plate in plate_l.filter(corrSpz=visitor.spz):
                    plate.visitor=visitor
                    plate.save()
                    print(str(plate) + "Druhe for")



            return redirect('polls:detail_visitor', spz=visitor.spz)
    else:
        form = VisitorForm()
    return render(request, 'polls/visitor_edit.html', {'form': form})

def visitor_edit(request,spz):
    visitor = get_object_or_404(Visitor, spz=spz)
    if request.method == "POST":
        form = VisitorForm(request.POST, instance=visitor)
        if form.is_valid():
            print ("je valiad edit")
            visitor = form.save(commit=False)
            visitor.save()
            return redirect('polls:detail_visitor', spz=visitor.spz)
    else:
        form = VisitorForm(instance=visitor)
    return render(request, 'polls/visitor_edit.html', {'form': form})


###################################################chybovu hlasku ak PK neexistuje
def detail_plate(request,pk):
    try:
        plate = Plate.objects.get(pk=pk)
        if request.method == "POST":
            form = PlateForm(request.POST, instance=plate)
            form.fields['corrSpz'].required = False
            if form.is_valid():

                plate = form.save(commit=False)
                print (plate.corrSpz)
                try:
                    if plate.corrSpz=='':
                        visitor = Visitor.objects.get(spz=plate.spz)
                    else:
                        visitor = Visitor.objects.get(spz=plate.corrSpz)
                except Visitor.DoesNotExist:
                    visitor = Visitor.objects.get(spz='BA000XX')
                plate.visitor = visitor
                plate.save()
                return redirect('polls:detail_plate', pk=plate.pk)
        else:
            form = PlateForm(instance=plate)
        return render(request, 'polls/detail_plate.html', {'plate' : plate,'form': form})
    except Visitor.DoesNotExist:
        print('exce')


    #return render(request, 'polls/detail_plate.html',{'plate' : plate})

polls/templates/base.html
{# HTML5 declaration #}
<!DOCTYPE html>
<html>
    {# Make modifiableczzzZZZzzead elements #}
    <head>
        <title>{% block title %}Ip Cam {% endblock title %} | Licence Plate</title>
        {% block head_favicon %}
          <link rel="icon" href="{{ STATIC_URL }}images/favicon.ico">

        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type"
                      content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {% block head_css %}
            {% block head_css_site %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
            <script src="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/master/src/js/bootstrap-datetimepicker.js"></script>
            <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"/>
            <link href="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/master/build/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
            <link href="{{STATIC_URL}}css/dashboard.css" rel="stylesheet">
            <link href="{{STATIC_URL}}css/jumbotron.css" rel="stylesheet">
            <link href="{{STATIC_URL}}css/sticky-footer.css" rel="stylesheet">
            <link href="{{STATIC_URL}}css/w3.css" rel="stylesheet">
            <!--link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">


            <!--link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">

            <link href="{{STATIC_URL}}css/datetimepicker.css" rel="stylesheet">
            <link href="{{STATIC_URL}}css/bootstrap-datetimepicker.css" rel="stylesheet">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

            <script src="{{STATIC_URL}}js/popper.min.js"></script>
            <script type="text/javascript" src="{{STATIC_URL}}js/bootstrap.js"></script>
            <script type="text/javascript" src="{{STATIC_URL}}js/bootstrap-datetimepicker.js"></script-->
            {% endblock head_css_site %}
            {% block head_css_section %}{% endblock head_css_section %}
            {% block head_css_page %}{% endblock head_css_page %}
        {% endblock head_css %}
    </head>


    <body>
    <div id="wrap">
    {# Navigation Menu #}
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" >IP CAM Plate Recognition</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/polls">Home</a></li>
            <li><a href="{% url 'polls:plates' %}">Zobrazit snimky </a></li>
            <li><a href="{% url 'polls:visitors' %}">Zobrazit uzivatelov</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hladat<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Hladat nevstevnika</a></li>
                <li><a href="#">Hladat zaznam</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nezaradene</li>
                <li><a href="#">Zobrazit nezaradene</a></li>
              </ul>
            </li>
          </ul>
          <!--form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form-->
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <header>


    </header>
    {# The Document Body #}
    <div id="site-wrapper">
        {% block content %}
            if you see this, something is wrong!
        {% endblock content %}
    </div>
    {# The Footer #}
      </div>
    <div id="footer">
      <div class="container">
        <p class="text-muted text-center credit">IP CAM Plate Recognition by <a href="http://ditis.sk">Ditis </a> and <a href="http://google.sk">vmec</a>.</p>
      </div>
    </div>
</body>



{# Set of blocks that can be used to display JavaScript files #}
{% block footer_javascript %}
    {% block footer_javascript_site %}


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{STATIC_URL}}js/ie10-viewport-bug-workaround.js"></script>
    {% endblock footer_javascript_site %}
    {% block footer_javascript_section %}{% endblock footer_javascript_section %}
    {% block footer_javascript_page %}{% endblock footer_javascript_page %}
{% endblock footer_javascript %}
</html>